//
//  PictureWithTitleCollectionRouter.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 12/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PictureWithTitleCollectionRouter: PictureWithTitleCollectionWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    func routeToMapDetailPage(dataDetail: DataPicture) {
//        let detailPageNavigator = MapDetailPageRouter.createModule(dataDetail: dataDetail)
        
        let detailPageNavigator = MapDetailPageRouter.createModuleAndDataPicture(dataDetail: dataDetail)
        
        detailPageNavigator.modalPresentationStyle = .fullScreen
        self.viewController?.navigationItem.backBarButtonItem = UIBarButtonItem(
            title: "Back", style: .plain, target: nil, action: nil)
        self.viewController?.navigationController?.pushViewController(detailPageNavigator, animated: true)
    }
    
    //insert parameter
    static func createModule() -> UIViewController {
        
        // Change to get view from storyboard if not using progammatic UI
        let view = PictureWithTitleCollectionViewController(nibName: nil, bundle: nil)
        let interactor = PictureWithTitleCollectionInteractor()
        let router = PictureWithTitleCollectionRouter()
        let presenter = PictureWithTitleCollectionPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return UINavigationController(rootViewController: view)
    }
}
