//
//  PictureWithTitleCollectionPresenter.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 12/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PictureWithTitleCollectionPresenter: PictureWithTitleCollectionPresenterProtocol {
    
    weak private var view: PictureWithTitleCollectionViewProtocol?
    var interactor: PictureWithTitleCollectionInteractorProtocol?
    private let router: PictureWithTitleCollectionWireframeProtocol

    init(interface: PictureWithTitleCollectionViewProtocol, interactor: PictureWithTitleCollectionInteractorProtocol?, router: PictureWithTitleCollectionWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getData(pictureData: [DataPicture]) {
        self.view?.showData(pictureData: pictureData)
    }
    
    func getDataFromInteractor() {
        self.interactor?.setData()
    }
    
    func notifyViewMapDetail(dataDetail: DataPicture) {
        self.router.routeToMapDetailPage(dataDetail: dataDetail)
    }
}
