//
//  MapDetailPagePresenter.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 25/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MapDetailPagePresenter: MapDetailPagePresenterProtocol {

    weak private var view: MapDetailPageViewProtocol?
    var interactor: MapDetailPageInteractorProtocol?
    private let router: MapDetailPageWireframeProtocol

    init(interface: MapDetailPageViewProtocol, interactor: MapDetailPageInteractorProtocol?, router: MapDetailPageWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getLocationDatafromInteractor() {
        self.interactor?.getLocation()
    }
    
    func getDataPictureDetail(pictureDetailData: [DataDetailPicture]) {
        self.view?.showData(dataPictureDetail: pictureDetailData)
    }
    
    func getDataPicture(dataPicture: DataPicture) {
        self.interactor?.setDataPictureDetail(dataPicture: dataPicture)
    }
    
    func notifyDisabledPopUp() {
        self.view?.showLocationDisabledPopUp()
    }
}
