//
//  MapDetailPageProtocols.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 25/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MapDetailPageWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol MapDetailPagePresenterProtocol: class {
    func getDataPicture (dataPicture: DataPicture)
    func notifyDisabledPopUp()
    func getLocationDatafromInteractor()
    func getDataPictureDetail(pictureDetailData: [DataDetailPicture])
}

//MARK: Interactor -
protocol MapDetailPageInteractorProtocol: class {

    var presenter: MapDetailPagePresenterProtocol?  { get set }
    func setDataPictureDetail(dataPicture: DataPicture)
    func getLocation()
}

//MARK: View -
protocol MapDetailPageViewProtocol: class {

    var presenter: MapDetailPagePresenterProtocol?  { get set }
    func showData(dataPictureDetail: [DataDetailPicture])
    func showLocationDisabledPopUp()
}
