//
//  TextCollectionProtocols.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 12/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TextCollectionWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol TextCollectionPresenterProtocol: class {

}

//MARK: Interactor -
protocol TextCollectionInteractorProtocol: class {

  var presenter: TextCollectionPresenterProtocol?  { get set }
}

//MARK: View -
protocol TextCollectionViewProtocol: class {

  var presenter: TextCollectionPresenterProtocol?  { get set }
}
