//
//  TextCollectionInteractor.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 12/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TextCollectionInteractor: TextCollectionInteractorProtocol {

    weak var presenter: TextCollectionPresenterProtocol?
}
