//
//  TextCollectionPresenter.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 12/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TextCollectionPresenter: TextCollectionPresenterProtocol {

    weak private var view: TextCollectionViewProtocol?
    var interactor: TextCollectionInteractorProtocol?
    private let router: TextCollectionWireframeProtocol

    init(interface: TextCollectionViewProtocol, interactor: TextCollectionInteractorProtocol?, router: TextCollectionWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}
