//
//  TextCollectionViewController.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 12/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TextCollectionViewController: UIViewController, TextCollectionViewProtocol {

	var presenter: TextCollectionPresenterProtocol?
    
    @IBOutlet weak var collectionView: UICollectionView!
    @IBOutlet weak var collectionLayout: UICollectionViewFlowLayout! {
        didSet {
            collectionLayout.estimatedItemSize = UICollectionViewFlowLayout.automaticSize
        }
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Text"
        navigationController?.navigationBar.backgroundColor = .secondarySystemBackground
        
        collectionView.register(TextCollectionViewCell.nib(), forCellWithReuseIdentifier: TextCollectionViewCell.identifier)
        collectionView.delegate = self
        collectionView.dataSource = self
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
    
        //ตรวจสอบ layout เมื่อมีการหมุน
        collectionView.collectionViewLayout.invalidateLayout()
        collectionView.reloadData()
    }

}

extension TextCollectionViewController: UICollectionViewDelegate {
    
}

extension TextCollectionViewController: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return text.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: Constants.reuseID, for: indexPath) as! TextCollectionViewCell
        
        cell.configure(with: text[indexPath.row])
        
        //set value to maxWidth
        cell.maxWidth = collectionView.bounds.width - Constants.spacing
        
        return cell
    }
}

private enum Constants {
    static let spacing: CGFloat = 20
    static let borderWidth: CGFloat = 0
    static let reuseID = "TextCollectionViewCell"
}
