//
//  SplashPageViewController.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 16/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashPageViewController: UIViewController, SplashPageViewProtocol {

	var presenter: SplashPagePresenterProtocol?

    @IBOutlet weak var indicator: UIActivityIndicatorView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        //กำหนดคุณลักษณะให้กับ splashPage
        let backgroundImage = UIImageView(frame: UIScreen.main.bounds)
        backgroundImage.image = UIImage(named: "background3")
        backgroundImage.contentMode = .scaleAspectFill
        
        self.view.insertSubview(backgroundImage, at: 0)
        self.showLoader()
        self.showTabBarAndPage()
        
    }
    
    //กำหนดคุณลักษณะให้ indicator สี, การเล่น animation หมุนโหลด
    func showLoader() {
        indicator.color = .white
        indicator.startAnimating()
    }
    
    //เรียกใช้ tabbarViewController หลังจาก splashPage ทำงานไปได้ 2 วิ
    func showTabBarAndPage() {
        
        //ขณะฟังก์ชั่นนี้เริ่มทำงานจะ +2 วิ เเล้วค่อยเรียกคำสั่งต่อไป
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(2), execute: {
            
            //เรียกฟังก์ชั่นที่อยู่ใน presenter
            self.presenter?.notifyTabBarView()
        })
    }

}
