//
//  SplashPagePresenter.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 16/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashPagePresenter: SplashPagePresenterProtocol {

    weak private var view: SplashPageViewProtocol?
    var interactor: SplashPageInteractorProtocol?
    private let router: SplashPageWireframeProtocol

    init(interface: SplashPageViewProtocol, interactor: SplashPageInteractorProtocol?, router: SplashPageWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    //เรียก func ที่อยู่ใน router
    func notifyTabBarView() {
        
        //เพราะเป็นการ route ไปที่หน้าต่างๆจึงอยู่ใน router
        self.router.tabBarViewController()
    }
}
