//
//  SplashPageProtocols.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 16/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SplashPageWireframeProtocol: class {
    func tabBarViewController()
}
//MARK: Presenter -
protocol SplashPagePresenterProtocol: class {
    func notifyTabBarView()
}

//MARK: Interactor -
protocol SplashPageInteractorProtocol: class {

    var presenter: SplashPagePresenterProtocol?  { get set }
}

//MARK: View -
protocol SplashPageViewProtocol: class {

    var presenter: SplashPagePresenterProtocol?  { get set }
}
