//
//  SplashPageRouter.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 16/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashPageRouter: SplashPageWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    func tabBarViewController() {
        
        //สร้างตัวแปรเรียกใช้ uitabbarView
        let tabBarVC = UITabBarController()
        
        //กำหนด viewController ต่างๆ
        let vcPictureAndText = PictureWithTitleCollectionRouter.createModule()
        let vcPicture = PictureCollectionRouter.createModule()
        let vcText = TextCollectionRouter.createModule()
        
        //กำหนด title ให้ viewController
        vcText.title = "Text"
        vcPicture.title = "Picture"
        vcPictureAndText.title = "Map With Name"
        
        //กำหนดคุณลักษณะให้กับ tabbarView
        tabBarVC.tabBar.backgroundColor = .secondarySystemBackground
        tabBarVC.setViewControllers([vcPictureAndText, vcPicture, vcText], animated: false)
        
        //item เพื่อเตรียมกำหนด icon ให้ tabbar
        guard let items = tabBarVC.tabBar.items else {
            return
        }
        
        //images array ของรูปไอคอนที่จะใช้
        let images = ["text.below.photo", "photo", "text.justify"]
        
        //ลูป array : จำนวน item = vc
        for x in 0..<items.count {
            
            //item[x] เเทน vc .image เพื่อใส่รูป icon = image ชื่อรูปที่อยูใน image
            items[x].image = UIImage(systemName: images[x])
        }
        
        //กำหนดให้การเปลี่ยนหน้า present เป็นแบบ fullscreen ios>13 จะเเสดงไม่เต็มจอ
        tabBarVC.modalPresentationStyle = .fullScreen;
        
        //เมื่อเรียกฟังก์ชั่นนี้จะเปลี่ยนหน้าไปตาม tabbar ที่ได้ setViewController ไปแล้ว โดนในที่นี้จะเริ่มต้นเปลี่ยนไปที่ vc1 ก่อน
        self.viewController?.present(tabBarVC, animated: true)
    }
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SplashPageViewController(nibName: nil, bundle: nil)
        let interactor = SplashPageInteractor()
        let router = SplashPageRouter()
        let presenter = SplashPagePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
