//
//  PictureCollectionProtocols.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 12/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PictureCollectionWireframeProtocol: class {

}
//MARK: Presenter -
protocol PictureCollectionPresenterProtocol: class {

}

//MARK: Interactor -
protocol PictureCollectionInteractorProtocol: class {

  var presenter: PictureCollectionPresenterProtocol?  { get set }
}

//MARK: View -
protocol PictureCollectionViewProtocol: class {

  var presenter: PictureCollectionPresenterProtocol?  { get set }
}
