//
//  PictureCollectionPresenter.swift
//  LearningCollectionViewApp
//
//  Created armyxx on 12/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PictureCollectionPresenter: PictureCollectionPresenterProtocol {

    weak private var view: PictureCollectionViewProtocol?
    var interactor: PictureCollectionInteractorProtocol?
    private let router: PictureCollectionWireframeProtocol

    init(interface: PictureCollectionViewProtocol, interactor: PictureCollectionInteractorProtocol?, router: PictureCollectionWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}
